# Generated by Django 4.0.4 on 2022-05-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(help_text='Documento do Cliente', max_length=20)),
                ('endereco', models.CharField(help_text='Endereco do Cliente', max_length=50)),
                ('cep', models.CharField(help_text='Cep do Cliente', max_length=20)),
                ('numero_residencia', models.CharField(help_text='Numero da Residencia do Cliente', max_length=20)),
                ('uf', models.CharField(help_text='Estado do Cliente', max_length=2)),
                ('telefone', models.CharField(help_text='Telefone do cliente', max_length=15)),
                ('senha', models.CharField(help_text='Senha do cliente', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição do Produto', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Itens_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.FloatField(help_text='Valor do produto', max_length=10)),
                ('quantidade', models.IntegerField(help_text='Quantidade de produtos')),
                ('desconto', models.FloatField(help_text='Valor do desconto', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField(help_text='Nome do Produto', max_length=200)),
                ('valor_unitario', models.FloatField(help_text='Valor do produto', max_length=10)),
                ('desconto', models.FloatField(help_text='Valor do desconto', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(help_text='Data do Pedido')),
                ('data_envio', models.DateField(help_text='Data dp Envio')),
                ('data_entrega', models.DateField(help_text='Data da Entrega')),
                ('frete', models.FloatField(help_text='Valor do Frete', max_length=10)),
                ('nome_destinatario', models.CharField(help_text='Nome do Destinatario', max_length=50)),
                ('endereco_destinatario', models.CharField(help_text='Endereco do Destinatario', max_length=50)),
                ('cep_destinatario', models.CharField(help_text='CEP do Destinatario', max_length=20)),
                ('documento', models.ForeignKey(help_text='Documento do Cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Desc_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_descricao', models.ForeignKey(help_text='id_descricao', on_delete=django.db.models.deletion.CASCADE, to='produtos.descricao')),
                ('id_produto', models.ForeignKey(help_text='id_produto', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
